// auto generated by go tool dist

package runtime

const defaultGoroot = `/home/eyberg/go/src/github.com/deferpanic/gorump/go`
const theVersion = `go1.5.1`
const goexperiment = ``
const stackGuardMultiplier = 1
var buildVersion = theVersion
