// auto generated by go tool dist

package sys

const DefaultGoroot = `/home/eyberg/go/src/github.com/deferpanic/gorump/1.7/go`
const TheVersion = `go1.7beta2`
const Goexperiment = ``
const StackGuardMultiplier = 1

